# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: devc

before:
  hooks:
    - go test ./...

builds:
  - main: .
    binary: devc
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/IsmailAki/devc/cmd.appVersion={{.Version}} -X github.com/IsmailAki/devc/cmd.commit={{.Commit}} -X github.com/IsmailAki/devc/cmd.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
